- Add --force and --verbose to 'rush get' command

diff --git a/rush b/rush
--- a/rush
+++ b/rush
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 0.8.4 (https://bashly.dannyb.co)
+# This script was generated by bashly 0.8.9 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n"
+  printf "bash version 4 or higher is required\n" >&2
   exit 1
 fi
 
@@ -28,8 +28,8 @@ rush_usage() {
   fi
 
   printf "Usage:\n"
-  printf "  rush [command]\n"
-  printf "  rush [command] --help | -h\n"
+  printf "  rush COMMAND\n"
+  printf "  rush [COMMAND] --help | -h\n"
   printf "  rush --version | -v\n"
   echo
   # :command.usage_commands
@@ -156,7 +156,7 @@ rush_remove_usage() {
   echo
 
   printf "Usage:\n"
-  printf "  rush remove REPO [options]\n"
+  printf "  rush remove REPO [OPTIONS]\n"
   printf "  rush remove --help | -h\n"
   echo
 
@@ -208,7 +208,7 @@ rush_clone_usage() {
   fi
 
   printf "Usage:\n"
-  printf "  rush clone GITHUB_USER [PATH] [options]\n"
+  printf "  rush clone GITHUB_USER [PATH] [OPTIONS]\n"
   printf "  rush clone --help | -h\n"
   echo
 
@@ -327,7 +327,7 @@ rush_push_usage() {
   echo
 
   printf "Usage:\n"
-  printf "  rush push [REPO] [options]\n"
+  printf "  rush push [REPO] [OPTIONS]\n"
   printf "  rush push --help | -h\n"
   echo
 
@@ -378,7 +378,7 @@ rush_config_usage() {
   echo
 
   printf "Usage:\n"
-  printf "  rush config [options]\n"
+  printf "  rush config [OPTIONS]\n"
   printf "  rush config --help | -h\n"
   echo
 
@@ -464,7 +464,7 @@ rush_get_usage() {
   echo
 
   printf "Usage:\n"
-  printf "  rush get PACKAGE [options]\n"
+  printf "  rush get PACKAGE [OPTIONS]\n"
   printf "  rush get --help | -h\n"
   echo
 
@@ -483,6 +483,16 @@ rush_get_usage() {
     printf "    Clone the repository if it is not found locally.\n    This flag will look for a GitHub user with the same name as the\n    repository, and attempt to clone their rush-repo repository.\n"
     echo
 
+    # :flag.usage
+    echo "  --force, -f"
+    printf "    Force installation.\n    This may mean different things in different packages.\n"
+    echo
+
+    # :flag.usage
+    echo "  --verbose, -v"
+    printf "    Show additional details if possible.\n"
+    echo
+
     # :command.usage_args
     printf "Arguments:\n"
 
@@ -494,7 +504,7 @@ rush_get_usage() {
     # :command.usage_examples
     printf "Examples:\n"
     printf "  rush ruby\n"
-    printf "  rush get ruby\n"
+    printf "  rush get ruby --force\n"
     printf "  rush get centos:ruby\n"
     echo
 
@@ -614,7 +624,7 @@ rush_copy_usage() {
   fi
 
   printf "Usage:\n"
-  printf "  rush copy SOURCE_PACKAGE [TARGET_PACKAGE] [options]\n"
+  printf "  rush copy SOURCE_PACKAGE [TARGET_PACKAGE] [OPTIONS]\n"
   printf "  rush copy --help | -h\n"
   echo
 
@@ -721,7 +731,7 @@ rush_list_usage() {
   echo
 
   printf "Usage:\n"
-  printf "  rush list [REPO_OR_PACKAGE] [options]\n"
+  printf "  rush list [REPO_OR_PACKAGE] [OPTIONS]\n"
   printf "  rush list --help | -h\n"
   echo
 
@@ -1219,7 +1229,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'get\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_rush_completions_filter "$(rush list -s -a) --clone --help -c -h")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_rush_completions_filter "$(rush list -s -a) --clone --force --help --verbose -c -f -h -v")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'a\'*)'
@@ -1239,7 +1249,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'g\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_rush_completions_filter "$(rush list -s -a) --clone --help -c -h")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_rush_completions_filter "$(rush list -s -a) --clone --force --help --verbose -c -f -h -v")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'u\'*)'
@@ -1481,6 +1491,8 @@ rush_get_command() {
   package=${args[package]}
   repo="default"
   clone=${args[--clone]}
+  export FORCE=${args['--force']}
+  export VERBOSE=${args['--verbose']}
 
   if [[ $package =~ (.*):(.*) ]]; then
     repo=${BASH_REMATCH[1]}
@@ -2023,7 +2035,7 @@ parse_requirements() {
 
   # :command.command_fallback
   "" )
-    rush_usage
+    rush_usage >&2
     exit 1
     ;;
 
@@ -2041,14 +2053,14 @@ parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
     * )
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
-      printf "invalid argument: %s\n" "$key"
+      printf "invalid argument: %s\n" "$key" >&2
       exit 1
 
       ;;
@@ -2079,7 +2091,7 @@ rush_add_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2095,7 +2107,7 @@ rush_add_parse_requirements() {
         args[path]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2105,11 +2117,11 @@ rush_add_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[repo]+x} ]]; then
-    printf "missing required argument: REPO\nusage: rush add REPO PATH\n"
+    printf "missing required argument: REPO\nusage: rush add REPO PATH\n" >&2
     exit 1
   fi
   if [[ -z ${args[path]+x} ]]; then
-    printf "missing required argument: PATH\nusage: rush add REPO PATH\n"
+    printf "missing required argument: PATH\nusage: rush add REPO PATH\n" >&2
     exit 1
   fi
 
@@ -2143,7 +2155,7 @@ rush_remove_parse_requirements() {
       ;;
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2155,7 +2167,7 @@ rush_remove_parse_requirements() {
         args[repo]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2165,7 +2177,7 @@ rush_remove_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[repo]+x} ]]; then
-    printf "missing required argument: REPO\nusage: rush remove REPO [options]\n"
+    printf "missing required argument: REPO\nusage: rush remove REPO [OPTIONS]\n" >&2
     exit 1
   fi
 
@@ -2216,7 +2228,7 @@ rush_clone_parse_requirements() {
         shift
         shift
       else
-        printf "%s\n" "--name requires an argument: --name, -n NAME"
+        printf "%s\n" "--name requires an argument: --name, -n NAME" >&2
         exit 1
       fi
       ;;
@@ -2238,7 +2250,7 @@ rush_clone_parse_requirements() {
       ;;
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2254,7 +2266,7 @@ rush_clone_parse_requirements() {
         args[path]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2264,7 +2276,7 @@ rush_clone_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[github_user]+x} ]]; then
-    printf "missing required argument: GITHUB_USER\nusage: rush clone GITHUB_USER [PATH] [options]\n"
+    printf "missing required argument: GITHUB_USER\nusage: rush clone GITHUB_USER [PATH] [OPTIONS]\n" >&2
     exit 1
   fi
 
@@ -2291,7 +2303,7 @@ rush_pull_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2303,7 +2315,7 @@ rush_pull_parse_requirements() {
         args[repo]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2351,13 +2363,13 @@ rush_push_parse_requirements() {
         shift
         shift
       else
-        printf "%s\n" "--message requires an argument: --message, -m TEXT"
+        printf "%s\n" "--message requires an argument: --message, -m TEXT" >&2
         exit 1
       fi
       ;;
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2369,7 +2381,7 @@ rush_push_parse_requirements() {
         args[repo]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2408,14 +2420,14 @@ rush_config_parse_requirements() {
       ;;
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
     * )
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
-      printf "invalid argument: %s\n" "$key"
+      printf "invalid argument: %s\n" "$key" >&2
       exit 1
 
       ;;
@@ -2446,7 +2458,7 @@ rush_default_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2458,7 +2470,7 @@ rush_default_parse_requirements() {
         args[repo]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2468,7 +2480,7 @@ rush_default_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[repo]+x} ]]; then
-    printf "missing required argument: REPO\nusage: rush default REPO\n"
+    printf "missing required argument: REPO\nusage: rush default REPO\n" >&2
     exit 1
   fi
 
@@ -2501,8 +2513,24 @@ rush_get_parse_requirements() {
       shift
       ;;
 
+    # :flag.case
+    --force | -f )
+
+      # :flag.case_no_arg
+      args[--force]=1
+      shift
+      ;;
+
+    # :flag.case
+    --verbose | -v )
+
+      # :flag.case_no_arg
+      args[--verbose]=1
+      shift
+      ;;
+
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2514,7 +2542,7 @@ rush_get_parse_requirements() {
         args[package]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2524,7 +2552,7 @@ rush_get_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[package]+x} ]]; then
-    printf "missing required argument: PACKAGE\nusage: rush get PACKAGE [options]\n"
+    printf "missing required argument: PACKAGE\nusage: rush get PACKAGE [OPTIONS]\n" >&2
     exit 1
   fi
 
@@ -2551,7 +2579,7 @@ rush_undo_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2563,7 +2591,7 @@ rush_undo_parse_requirements() {
         args[package]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2573,7 +2601,7 @@ rush_undo_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[package]+x} ]]; then
-    printf "missing required argument: PACKAGE\nusage: rush undo PACKAGE\n"
+    printf "missing required argument: PACKAGE\nusage: rush undo PACKAGE\n" >&2
     exit 1
   fi
 
@@ -2600,7 +2628,7 @@ rush_snatch_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2616,7 +2644,7 @@ rush_snatch_parse_requirements() {
         args[package]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2626,11 +2654,11 @@ rush_snatch_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[github_user]+x} ]]; then
-    printf "missing required argument: GITHUB_USER\nusage: rush snatch GITHUB_USER PACKAGE\n"
+    printf "missing required argument: GITHUB_USER\nusage: rush snatch GITHUB_USER PACKAGE\n" >&2
     exit 1
   fi
   if [[ -z ${args[package]+x} ]]; then
-    printf "missing required argument: PACKAGE\nusage: rush snatch GITHUB_USER PACKAGE\n"
+    printf "missing required argument: PACKAGE\nusage: rush snatch GITHUB_USER PACKAGE\n" >&2
     exit 1
   fi
 
@@ -2664,7 +2692,7 @@ rush_copy_parse_requirements() {
       ;;
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2680,7 +2708,7 @@ rush_copy_parse_requirements() {
         args[target_package]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2690,7 +2718,7 @@ rush_copy_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[source_package]+x} ]]; then
-    printf "missing required argument: SOURCE_PACKAGE\nusage: rush copy SOURCE_PACKAGE [TARGET_PACKAGE] [options]\n"
+    printf "missing required argument: SOURCE_PACKAGE\nusage: rush copy SOURCE_PACKAGE [TARGET_PACKAGE] [OPTIONS]\n" >&2
     exit 1
   fi
 
@@ -2717,7 +2745,7 @@ rush_info_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2729,7 +2757,7 @@ rush_info_parse_requirements() {
         args[package]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2739,7 +2767,7 @@ rush_info_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[package]+x} ]]; then
-    printf "missing required argument: PACKAGE\nusage: rush info PACKAGE\n"
+    printf "missing required argument: PACKAGE\nusage: rush info PACKAGE\n" >&2
     exit 1
   fi
 
@@ -2781,7 +2809,7 @@ rush_list_parse_requirements() {
       ;;
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2793,7 +2821,7 @@ rush_list_parse_requirements() {
         args[repo_or_package]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2825,7 +2853,7 @@ rush_search_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2837,7 +2865,7 @@ rush_search_parse_requirements() {
         args[text]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2847,7 +2875,7 @@ rush_search_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[text]+x} ]]; then
-    printf "missing required argument: TEXT\nusage: rush search TEXT\n"
+    printf "missing required argument: TEXT\nusage: rush search TEXT\n" >&2
     exit 1
   fi
 
@@ -2874,7 +2902,7 @@ rush_edit_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2890,7 +2918,7 @@ rush_edit_parse_requirements() {
         args[file]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2900,7 +2928,7 @@ rush_edit_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[package]+x} ]]; then
-    printf "missing required argument: PACKAGE\nusage: rush edit PACKAGE [FILE]\n"
+    printf "missing required argument: PACKAGE\nusage: rush edit PACKAGE [FILE]\n" >&2
     exit 1
   fi
 
@@ -2927,7 +2955,7 @@ rush_show_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
@@ -2943,7 +2971,7 @@ rush_show_parse_requirements() {
         args[file]=$1
         shift
       else
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
       fi
 
@@ -2953,7 +2981,7 @@ rush_show_parse_requirements() {
   done
   # :command.required_args_filter
   if [[ -z ${args[package]+x} ]]; then
-    printf "missing required argument: PACKAGE\nusage: rush show PACKAGE [FILE]\n"
+    printf "missing required argument: PACKAGE\nusage: rush show PACKAGE [FILE]\n" >&2
     exit 1
   fi
 
@@ -2980,14 +3008,14 @@ rush_completions_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
+      printf "invalid option: %s\n" "$key" >&2
       exit 1
       ;;
 
     * )
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
-      printf "invalid argument: %s\n" "$key"
+      printf "invalid argument: %s\n" "$key" >&2
       exit 1
 
       ;;
