initial snatch implementation

diff --git a/rush b/rush
--- a/rush
+++ b/rush
@@ -36,6 +36,7 @@ rush_usage() {
   printf "\nPackage Commands:\n"
   echo "  get       Install a package (default)"
   echo "  undo      Uninstall a package"
+  echo "  snatch    Install a package from a remote repo"
   echo "  info      Show information about a package"
   echo "  list      Show packages in one or all repositories"
   echo "  search    Search in package names and info files"
@@ -444,6 +445,53 @@ rush_undo_usage() {
     
     printf "  rush undo ruby\n"
     printf "  rush undo centos:ruby\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+rush_snatch_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "rush snatch\n"
+    echo 
+    printf "  Install a package from a remote repo\n  This command is a shortcut to running clone followed by get.\n  It will clone the repository to a temporary directory and run the main\n  package script.\n"
+    echo 
+  else
+    printf "rush snatch - Install a package from a remote repo\n"
+    echo 
+  fi
+
+  printf "Usage:\n"
+  printf "  rush snatch GITHUB_USER PACKAGE\n"
+  printf "  rush snatch --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "Arguments:\n"
+    
+    # :argument.usage
+    echo "  GITHUB_USER"
+    printf "    Github user\n    This user is expected to have a repository named 'rush-repo'.\n    If you need to use a different name, use the 'user/repo' syntax.\n"
+    echo
+    
+    # :argument.usage
+    echo "  PACKAGE"
+    printf "    Package name\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+    
+    printf "  rush snatch james python\n"
+    printf "  rush snatch james/other-rush-repo python\n"
     echo
 
   fi
@@ -1001,6 +1049,52 @@ rush_undo_command() {
 }
 
 # :command.function
+rush_snatch_command() {
+  # :src/snatch_command.sh
+  # Collect variables
+  repo_id=${args[github_user]}
+  package=${args[package]}
+  
+  # Cleanup function
+  cleanup () {
+    [[ $repo_path ]] || return
+    rm -rf $repo_path &> /dev/null
+  }
+  
+  # Adjust repo_id - defaults to $user/rush-repo
+  [[ $repo_id = */* ]] || repo_id="$repo_id/rush-repo"
+  
+  # Set clone URL - ssh or https?
+  repo_url=https://github.com/$repo_id.git
+  
+  set -e
+  
+  # Set clone path and register cleanup function
+  repo_path=$(mktemp -d -t rush-XXXXXXXXXX)
+  trap cleanup EXIT ERR INT TERM
+  
+  # Clone
+  git clone --depth 1 "$repo_url" "$repo_path"
+  
+  # Set package variables
+  package_path=$repo_path/$package
+  script=$package_path/main
+  
+  # Verify we have everything we need
+  [[ -d $package_path ]] || abort "package not found: $repo_id $package"
+  [[ -f $script ]] || abort "script not found: $script"
+  
+  # Run the script (make it executable if it isnt first)
+  export REPO="$repo"
+  export REPO_PATH="$repo_path"
+  [[ -z "$USER_CWD" ]] && export USER_CWD="$PWD"
+  echo "run $(green "$repo_id $package")"
+  [[ -x "$script" ]] || chmod u+x "$script"
+  cd "$package_path"
+  ./main
+}
+
+# :command.function
 rush_info_command() {
   # :src/info_command.sh
   # Collect variables
@@ -1274,6 +1368,13 @@ parse_requirements() {
     action="undo"
     shift
     rush_undo_parse_requirements "$@"
+    shift $#
+    ;;    
+  
+  snatch )
+    action="snatch"
+    shift
+    rush_snatch_parse_requirements "$@"
     shift $#
     ;;    
   
@@ -1866,6 +1967,72 @@ rush_undo_parse_requirements() {
 }
 
 # :command.parse_requirements
+rush_snatch_parse_requirements() {
+  # :command.fixed_flag_filter
+  case "$1" in
+  --version | -v )
+    version_command
+    exit
+    ;;
+  
+  --help | -h )
+    long_usage=yes
+    rush_snatch_usage
+    exit 1
+    ;;
+  
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="snatch"
+  # :command.required_args_filter
+  if [[ $1 && $1 != -* ]]; then
+    args[github_user]=$1
+    shift
+  else
+    printf "missing required argument: GITHUB_USER\nusage: rush snatch GITHUB_USER PACKAGE\n"
+    exit 1
+  fi
+  
+  if [[ $1 && $1 != -* ]]; then
+    args[package]=$1
+    shift
+  else
+    printf "missing required argument: PACKAGE\nusage: rush snatch GITHUB_USER PACKAGE\n"
+    exit 1
+  fi
+  # :command.required_flags_filter
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+  
+    -* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+  
+    * )
+      # :command.parse_requirements_case
+      if [[ ! ${args[github_user]} ]]; then
+        args[github_user]=$1
+        shift
+      elif [[ ! ${args[package]} ]]; then
+        args[package]=$1
+        shift
+      else
+        printf "invalid argument: %s\n" "$key"
+        exit 1
+      fi
+      ;;
+  
+    esac
+  done
+  # :command.default_assignments
+}
+
+# :command.parse_requirements
 rush_info_parse_requirements() {
   # :command.fixed_flag_filter
   case "$1" in
@@ -2178,6 +2345,14 @@ run() {
       rush_undo_usage
     else
       rush_undo_command
+    fi
+  
+  elif [[ $action == "snatch" ]]; then
+    if [[ ${args[--help]} ]]; then
+      long_usage=yes
+      rush_snatch_usage
+    else
+      rush_snatch_command
     fi
   
   elif [[ $action == "info" ]]; then
