- Implement full bash completion

diff --git a/rush b/rush
--- a/rush
+++ b/rush
@@ -24,25 +24,27 @@ rush_usage() {
   echo
   # :command.usage_commands
   printf "Repository Commands:\n"
-  echo "  add       Register a local repository"
-  echo "  remove    Unregister a local repository"
+  echo "  add           Register a local repository"
+  echo "  remove        Unregister a local repository"
   printf "\nGit Commands:\n"
-  echo "  clone     Clone a GitHub package repository"
-  echo "  pull      Git pull one or all repositories"
-  echo "  push      Git push one or all repositories"
+  echo "  clone         Clone a GitHub package repository"
+  echo "  pull          Git pull one or all repositories"
+  echo "  push          Git push one or all repositories"
   printf "\nConfig Commands:\n"
-  echo "  config    Show or edit the configuration file"
-  echo "  default   Set a default repository"
+  echo "  config        Show or edit the configuration file"
+  echo "  default       Set a default repository"
   printf "\nPackage Commands:\n"
-  echo "  get       Install a package (default)"
-  echo "  undo      Uninstall a package"
-  echo "  snatch    Install a package from a remote repo"
-  echo "  copy      Copy a package between local repositories"
-  echo "  info      Show information about a package"
-  echo "  list      Show packages in one or all repositories"
-  echo "  search    Search in package names and info files"
-  echo "  edit      Edit package files"
-  echo "  show      Show package files"
+  echo "  get           Install a package (default)"
+  echo "  undo          Uninstall a package"
+  echo "  snatch        Install a package from a remote repo"
+  echo "  copy          Copy a package between local repositories"
+  echo "  info          Show information about a package"
+  echo "  list          Show packages in one or all repositories"
+  echo "  search        Search in package names and info files"
+  echo "  edit          Edit package files"
+  echo "  show          Show package files"
+  printf "\nInternal Commands:\n"
+  echo "  completions   Generate bash completions"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -791,6 +793,31 @@ rush_show_usage() {
   fi
 }
 
+# :command.usage
+rush_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "rush completions - Generate bash completions\n"
+    echo 
+  else
+    printf "rush completions - Generate bash completions\n"
+    echo 
+  fi
+
+  printf "Usage:\n"
+  printf "  rush completions\n"
+  printf "  rush completions --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
 # :command.inspect_args
 inspect_args() {
   readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
@@ -988,6 +1015,41 @@ is_busybox_grep() {
 # :src/lib/say.sh
 say() {
   printf "%-20s | %s\n" "$(magenta "$1")" "$(bold "${*:2}")"
+}
+
+# :src/lib/send_completions.sh
+send_completions() {
+  echo $'#!/usr/bin/env bash'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $'_rush_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $''
+  echo $'  case "$COMP_LINE" in'
+  echo $'    \'rush completions\'*) COMPREPLY=($(compgen -W "--help -h" -- "$cur")) ;;'
+  echo $'    \'rush default\'*) COMPREPLY=($(compgen -W "--help -h" -- "$cur")) ;;'
+  echo $'    \'rush remove\'*) COMPREPLY=($(compgen -W "--help --purge -h -p" -- "$cur")) ;;'
+  echo $'    \'rush config\'*) COMPREPLY=($(compgen -W "--edit --help -e -h" -- "$cur")) ;;'
+  echo $'    \'rush snatch\'*) COMPREPLY=($(compgen -W "--help -h" -- "$cur")) ;;'
+  echo $'    \'rush search\'*) COMPREPLY=($(compgen -W "--help -h" -- "$cur")) ;;'
+  echo $'    \'rush clone\'*) COMPREPLY=($(compgen -A directory -W "--default --help --ignore --name --shallow --ssh -d -h -i -n -s -w" -- "$cur")) ;;'
+  echo $'    \'rush pull\'*) COMPREPLY=($(compgen -W "--help -h" -- "$cur")) ;;'
+  echo $'    \'rush push\'*) COMPREPLY=($(compgen -W "--all --help --message -a -h -m" -- "$cur")) ;;'
+  echo $'    \'rush undo\'*) COMPREPLY=($(compgen -W "$(rush list -s) --help -h" -- "$cur")) ;;'
+  echo $'    \'rush copy\'*) COMPREPLY=($(compgen -W "$(rush list -s) --force --help -f -h" -- "$cur")) ;;'
+  echo $'    \'rush info\'*) COMPREPLY=($(compgen -W "$(rush list -s) --help -h" -- "$cur")) ;;'
+  echo $'    \'rush list\'*) COMPREPLY=($(compgen -W "--help --simple -h -s" -- "$cur")) ;;'
+  echo $'    \'rush edit\'*) COMPREPLY=($(compgen -W "$(rush list -s) --help -h" -- "$cur")) ;;'
+  echo $'    \'rush show\'*) COMPREPLY=($(compgen -W "$(rush list -s) --help -h" -- "$cur")) ;;'
+  echo $'    \'rush add\'*) COMPREPLY=($(compgen -A directory -W "--help -h" -- "$cur")) ;;'
+  echo $'    \'rush get\'*) COMPREPLY=($(compgen -W "$(rush list -s) --clone --help -c -h" -- "$cur")) ;;'
+  echo $'    \'rush\'*) COMPREPLY=($(compgen -W "$(rush list -s) --help --version -h -v add clone completions config copy default edit get info list pull push remove search show snatch undo" -- "$cur")) ;;'
+  echo $'  esac'
+  echo $'}'
+  echo $''
+  echo $'complete -F _rush_completions rush'
 }
 
 # :src/lib/warn.sh
@@ -1568,6 +1630,12 @@ rush_show_command() {
   fi
 }
 
+# :command.function
+rush_completions_command() {
+  # :src/completions_command.sh
+  send_completions
+}
+
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flag_filter
@@ -1702,6 +1770,13 @@ parse_requirements() {
     action="show"
     shift
     rush_show_parse_requirements "$@"
+    shift $#
+    ;;    
+  
+  completions )
+    action="completions"
+    shift
+    rush_completions_parse_requirements "$@"
     shift $#
     ;;    
   
@@ -2723,6 +2798,50 @@ rush_show_parse_requirements() {
   # :command.whitelist_filter
 }
 
+# :command.parse_requirements
+rush_completions_parse_requirements() {
+  # :command.fixed_flag_filter
+  case "$1" in
+  --version | -v )
+    version_command
+    exit
+    ;;
+  
+  --help | -h )
+    long_usage=yes
+    rush_completions_usage
+    exit 1
+    ;;
+  
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="completions"
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+  
+    -* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+  
+    * )
+      # :command.parse_requirements_case
+      printf "invalid argument: %s\n" "$key"
+      exit 1
+      ;;
+  
+    esac
+  done
+  # :command.default_assignments
+  # :command.whitelist_filter
+}
+
 # :command.initialize
 initialize() {
   version="0.6.4"
@@ -2865,6 +2984,14 @@ run() {
       rush_show_usage
     else
       rush_show_command
+    fi
+  
+  elif [[ $action == "completions" ]]; then
+    if [[ ${args[--help]} ]]; then
+      long_usage=yes
+      rush_completions_usage
+    else
+      rush_completions_command
     fi
   
   elif [[ $action == "root" ]]; then
